language: python
sudo: false
python:
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.7"
      dist: xenial
      sudo: required
      install: pip install black==18.6b4
      script: black --check --verbose rohrpost
      after_success: true
install:
    - pip install -U pip wheel setuptools
    - pip install coveralls
    - pip install -r requirements/dev.txt
    - pip install -r doc/requirements.txt
script:
    - pylava .
    - isort -rc -c .
    - pytest --cov-report term-missing --cov=rohrpost tests
    - cd doc && make html
after_success:
    - coveralls
cache:
    directories:
        - $HOME/.cache/pip
