language: python
sudo: false
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -U pip wheel setuptools
    - pip install coveralls
    - pip install -r requirements/dev.txt
    - pip install -r doc/requirements.txt
script:
    - pylama .
    - isort -rc -c .
    - pytest --cov-report term-missing --cov=rohrpost tests
    - cd doc && make html
after_success:
    - coveralls
cache:
    directories:
        - $HOME/.cache/pip
