language: python
sudo: false
python:
    - "3.5"
    - "3.6"
install:
    - pip install -U pip wheel setuptools
    - pip install -r requirements/dev.txt
script:
    - pylama .
    - isort -rc -c .
    - pytest --cov-report term-missing --cov=rohrpost tests
cache:
    directories:
        - $HOME/.cache/pip
