---
name: Build and upload Python Package

'on':
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy  # only the deploy environment has `secrets.PYPI_TOKEN`

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version-file: "pyproject.toml"
      - name: Build package
        run: |
          uv build
      - name: Check long description
        run: uv run --only-group publish twine check dist/*
      - name: Publish package on PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv run --only-group publish twine upload dist/*
