---
name: Tests

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.6
        - 3.7
        - 3.8
        - 3.9

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install coveralls
          python -m pip install -r requirements/dev.txt
      - name: Run tests
        run: |
          python -m pytest --cov-report term-missing --cov=rohrpost tests
      - name: Publish coverage
        run: |
          echo "TODO: Run 'coveralls'"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements/dev.txt
      - name: Lint code
        run: |
          pylava .
          isort --check --diff .
          black --check --verbose --diff rohrpost tests

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r doc/requirements.txt
      - name: Build documentation
        run: cd doc && make html
